### ISSUE TITLE
Static deployment shows blank pages 

### ISSUE THREAD

**Issue by marco-land** [johannschopplich/nuxt-kql#10]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.6.7`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `nitro`, `experimental`
- Runtime Modules:  `nuxt-kql@0.27.1`
- Build Modules:    `-`

### Reproduction

[GtHub Repo](https://github.com/marco-land/nuxt-kql-static) / [Netlify Deploy](https://nuxt-kql-static.netlify.app)

### Describe the bug

My pages remain blank when running `npm generate`

**Comment by johannschopplich** [comment]
Have you made sure that your environment variables are set on your production environment (Netlify) before building the static bundle? 

For example, I have used the public Cacao Kit `.env` file as an example (while changing Kirby auth to `bearer`):
```diff
+kql: {
+  auth: "bearer"
+},
```

Running the generate script will write an HTML and payload JSON file for each route. Running a web server locally will successfully fetch the prerendered data:

```bash
npm run generate
cd .output/public
python3 -m http.server
```

Reference:

<img width="577" alt="Bildschirmfoto 2023-06-09 um 16 53 08" src="https://github.com/johannschopplich/nuxt-kql/assets/27850750/fefa5ad1-6919-4e1d-9f6b-851bff242146">

**Comment by marco-land** [comment]
🙈 Indeed in my minimal setup the case... Works all fine -- somehow on localhost, it remains blank, but feel free to close this issue. This seems to be something else then.
Thanks!

**Comment by johannschopplich** [comment]
OK, I hope you will find the issue then. 🙆‍♂️

**Comment by johannschopplich** [comment]
Interesting. Thanks for the thorough reproduction. I'm unsure what causes the issue. 

It seems like the payload is not written or used for the given localised calls.

**Comment by johannschopplich** [comment]
@marco-land I have found the bug. There is an issue with your code. You're trying to pass a reactive computed variable as the `language`, which requires a string. If you use TypeScript, the issue comes apparent pretty quick:

<img width="856" alt="grafik" src="https://github.com/johannschopplich/nuxt-kql/assets/27850750/f1a05e35-8679-4348-a57e-7fdab853f572">

Thus, you have to use `locale.value` when passing using it for the query `language`. I can't recommend TypeScript enough – for simple issues like these, it is a time saver. 🙂

**Comment by marco-land** [comment]
Oh yes!

Good point regarding TS 🫣
